---
name: add_run_directory
pack: gmc_norr_seqdata
enabled: true

trigger:
  type: gmc_norr_seqdata.new_directory

criteria:
  trigger.directory_type:
    type: equals
    pattern: run
  trigger.state:
    type: inside
    pattern: [new, ready, pending]

action:
  ref: gmc_norr_seqdata.add_run
  parameters:
    runparameters: "{{ trigger.runparameters }}"
    path: "{{ trigger.path }}"
    state: "{{ trigger.state }}"
