---
name: add_run_qc
description: Rule for adding QC data to a sequencing run
pack: gmc_norr_seqdata
enabled: true

trigger:
  type: gmc_norr_seqdata.state_change

criteria:
  trigger.directory_type:
    type: equals
    pattern: run
  trigger.state:
    type: equals
    pattern: ready

action:
  ref: gmc_norr_seqdata.add_run_qc
  parameters:
    run_id: "{{ trigger.run_id }}"
