---
name: copy_indexmetrics
description: Rule for copying the IndexMetricsOut.bin file from a NovaSeq run to the InterOp folder on the shared drive
pack: gmc_norr_seqdata
enabled: true

trigger:
  type: cleve.analysis_state_update

criteria:
  trigger.state:
    type: equals
    pattern: ready
  trigger.software:
    type: contains
    pattern: BCLConvert

action:
  ref: gmc_norr_seqdata.copy_indexmetrics
  parameters:
    analysis_id: "{{ trigger.analysis_id }}"
    destinations: "{{ config_context.shared_drive | tojson }}"
