---
name: copy_indexmetrics
description: Rule for copying the IndexMetricsOut.bin file from a NovaSeq run to the InterOp folder on the shared drive
pack: gmc_norr_seqdata
enabled: true

trigger:
  type: gmc_norr_seqdata.state_change

criteria:
  trigger.directory_type:
    type: equals
    pattern: analysis
  trigger.state:
    type: equals
    pattern: ready

action:
  ref: gmc_norr_seqdata.copy_indexmetrics
  parameters:
    path: "{{ trigger.path }}"
    target_directory: "{{ trigger.target_directory }}"
