---
name: copy_indexmetrics
description: >
  Rule for checking if a BCLConvert run belongs to a
  lymphotrack sequenicng run, and if so, move the fastq
  folder to a shared directory
pack: gmc_norr_seqdata
enabled: true

trigger:
  type: cleve.analysis_state_update

criteria:
  trigger.state:
    type: equals
    pattern: ready
  trigger.software:
    type: contains
    pattern: BCLConvert
  trigger.path:
    type: contains
    pattern: miseq

action:
  ref: gmc_norr_seqdata.copy_lymphotrack
  parameters:
    analysis_id: "{{ trigger.analysis_id }}"
