name: copy_interop
description: Rule for copying the InterOp folder from a NovaSeq run to the shared drive
pack: gmc_norr_seqdata
enabled: true

trigger:
  type: cleve.run_state_update

criteria:
  trigger.state:
    type: equals
    pattern: ready

action:
  ref: gmc_norr_seqdata.copy_interop
  parameters:
    run_path: "{{ trigger.path }}"
    platform: "{{ trigger.platform }}"
    destinations: "{{ config_context.shared_drive | tojson }}"
