name: copy_interop
description: Rule for copying the InterOp folder from a NovaSeq run to the shared drive
pack: gmc_norr_seqdata
enabled: true

trigger:
  type: gmc_norr_seqdata.state_change

criteria:
  trigger.directory_type:
    type: equals
    pattern: run
  trigger.platform:
    type: equals
    pattern: "NovaSeq X Plus"
  trigger.state:
    type: equals
    pattern: ready

action:
  ref: gmc_norr_seqdata.copy_interop
  parameters:
    path: "{{ trigger.path }}"
    target_directory: "{{ trigger.target_directory }}"
