---
name: update_run_state
description: Rule for when the state of a run directory is updated
pack: gmc_norr_seqdata
enabled: true

trigger:
  type: gmc_norr_seqdata.state_change

criteria:
  trigger.directory_type:
    type: equals
    pattern: run

action:
  ref: gmc_norr_seqdata.run_state_workflow
  parameters:
    run_id: "{{ trigger.run_id }}"
    state: "{{ trigger.state }}"
    path: "{{ trigger.path | use_none }}"
