---
name: update_run_path
description: Rule for updating the path of an existing sequencing run
pack: gmc_norr_seqdata
enabled: true

trigger:
  type: gmc_norr_seqdata.state_change

criteria:
  trigger.directory_type:
    type: equals
    pattern: run
  trigger.state:
    type: equals
    pattern: moved

action:
  ref: gmc_norr_seqdata.update_run_path
  parameters:
    run_id: "{{ trigger.run_id }}"
    path: "{{ trigger.path | use_none }}"
